import { Quote } from "lucide-react";

const QUOTES = [
  { text: "Here's looking at you, kid.", film: "Casablanca" },
  { text: "May the Force be with you.", film: "Star Wars" },
  { text: "After all, tomorrow is another day!", film: "Gone with the Wind" },
  { text: "I'm gonna make him an offer he can't refuse.", film: "The Godfather" },
  { text: "You talking to me?", film: "Taxi Driver" },
  { text: "What we do in life echoes in eternity.", film: "Gladiator" },
  { text: "To infinity and beyond!", film: "Toy Story" },
  { text: "Life is like a box of chocolates. You never know what you're gonna get.", film: "Forrest Gump" },
  { text: "Why so serious?", film: "The Dark Knight" },
  { text: "I see dead people.", film: "The Sixth Sense" },
  { text: "Keep your friends close, but your enemies closer.", film: "The Godfather Part II" },
  { text: "Roads? Where we're going we don't need roads.", film: "Back to the Future" },
  { text: "I feel the need... the need for speed.", film: "Top Gun" },
  { text: "You can't handle the truth!", film: "A Few Good Men" },
  { text: "I'll be back.", film: "The Terminator" },
  { text: "Just keep swimming.", film: "Finding Nemo" },
  { text: "The first rule of Fight Club is: you do not talk about Fight Club.", film: "Fight Club" },
  { text: "It's not who I am underneath, but what I do that defines me.", film: "Batman Begins" },
  { text: "I'm the king of the world!", film: "Titanic" },
  { text: "There's no place like home.", film: "The Wizard of Oz" },
  { text: "Say hello to my little friend!", film: "Scarface" },
  { text: "My mama always said life was like a box of chocolates.", film: "Forrest Gump" },
  { text: "I wish I knew how to quit you.", film: "Brokeback Mountain" },
  { text: "Carpe diem. Seize the day, boys.", film: "Dead Poets Society" },
  { text: "Here's Johnny!", film: "The Shining" },
  { text: "Elementary, my dear Watson.", film: "Sherlock Holmes" },
  { text: "It's alive! It's alive!", film: "Frankenstein" },
  { text: "My precious.", film: "The Lord of the Rings" },
  { text: "I am Groot.", film: "Guardians of the Galaxy" },
  { text: "Hasta la vista, baby.", film: "Terminator 2: Judgment Day" },
  { text: "You shall not pass!", film: "The Lord of the Rings: The Fellowship of the Ring" },
  { text: "With great power comes great responsibility.", film: "Spider-Man" },
  { text: "I am Iron Man.", film: "The Avengers" },
  { text: "It's showtime.", film: "Beetlejuice" },
  { text: "I'll have what she's having.", film: "When Harry Met Sally" },
  { text: "Frankly, my dear, I don't give a damn.", film: "Gone with the Wind" },
  { text: "You're gonna need a bigger boat.", film: "Jaws" },
  { text: "Houston, we have a problem.", film: "Apollo 13" },
  { text: "Nobody puts Baby in a corner.", film: "Dirty Dancing" },
  { text: "I drink your milkshake!", film: "There Will Be Blood" },
  { text: "We're not in Kansas anymore.", film: "The Wizard of Oz" },
  { text: "Wakanda forever!", film: "Black Panther" },
  { text: "I am your father.", film: "The Empire Strikes Back" },
  { text: "The truth is... I am Iron Man.", film: "Iron Man" },
  { text: "A martini. Shaken, not stirred.", film: "Goldfinger" },
  { text: "I coulda been a contender.", film: "On the Waterfront" },
  { text: "Wax on, wax off.", film: "The Karate Kid" },
  { text: "That'll do, pig. That'll do.", film: "Babe" },
  { text: "E.T. phone home.", film: "E.T. the Extra-Terrestrial" },
  { text: "As if!", film: "Clueless" },
  { text: "I volunteer as tribute!", film: "The Hunger Games" },
  { text: "Do or do not. There is no try.", film: "The Empire Strikes Back" },
  { text: "This is the way.", film: "The Mandalorian" },
  { text: "They may take our lives, but they'll never take our freedom!", film: "Braveheart" },
  { text: "I'm not a smart man, but I know what love is.", film: "Forrest Gump" },
  { text: "The stuff that dreams are made of.", film: "The Maltese Falcon" },
  { text: "Every passing minute is another chance to turn it all around.", film: "Vanilla Sky" },
  { text: "Hope is a good thing, maybe the best of things.", film: "The Shawshank Redemption" },
  { text: "Not all those who wander are lost.", film: "The Lord of the Rings" },
  { text: "Oh yes, the past can hurt. But the way I see it, you can either run from it, or learn from it.", film: "The Lion King" },
  { text: "Some people can't believe in themselves until someone else believes in them first.", film: "Good Will Hunting" },
  { text: "It is not our abilities that show what we truly are. It is our choices.", film: "Harry Potter and the Chamber of Secrets" },
  { text: "To see the world, things dangerous to come to, to see behind walls, to draw closer.", film: "The Secret Life of Walter Mitty" },
  { text: "The greatest trick the Devil ever pulled was convincing the world he didn't exist.", film: "The Usual Suspects" },
  { text: "I'm having an old friend for dinner.", film: "The Silence of the Lambs" },
  { text: "Get busy living, or get busy dying.", film: "The Shawshank Redemption" },
  { text: "I love the smell of napalm in the morning.", film: "Apocalypse Now" },
  { text: "Rosebud.", film: "Citizen Kane" },
  { text: "Badges? We ain't got no badges!", film: "The Treasure of the Sierra Madre" },
  { text: "You had me at hello.", film: "Jerry Maguire" },
  { text: "Show me the money!", film: "Jerry Maguire" },
  { text: "Nobody's perfect.", film: "Some Like It Hot" },
  { text: "I see now that the circumstances of one's birth are irrelevant. It is what you do with the gift of life that determines who you are.", film: "Mewtwo Strikes Back" },
  { text: "After all this time? Always.", film: "Harry Potter and the Deathly Hallows" },
  { text: "Ogres are like onions.", film: "Shrek" },
  { text: "To me, you are perfect.", film: "Love Actually" },
  { text: "I'm just a girl, standing in front of a boy, asking him to love her.", film: "Notting Hill" },
  { text: "Chewie, we're home.", film: "Star Wars: The Force Awakens" },
  { text: "Why do we fall? So we can learn to pick ourselves up.", film: "Batman Begins" },
  { text: "In case I don't see ya: good afternoon, good evening, and good night!", film: "The Truman Show" },
  { text: "There is no spoon.", film: "The Matrix" },
  { text: "I'm walking here!", film: "Midnight Cowboy" },
  { text: "What's so great about being a grownup anyway?", film: "Big" },
  { text: "I wish I were big.", film: "Big" },
  { text: "Shimmy Shimmy Cocoa Puff.", film: "Big" },
  { text: "You is kind. You is smart. You is important.", film: "The Help" },
  { text: "Fasten your seatbelts. It's going to be a bumpy night.", film: "All About Eve" },
  { text: "We accept the love we think we deserve.", film: "The Perks of Being a Wallflower" },
  { text: "Life moves pretty fast. If you don't stop and look around once in a while, you could miss it.", film: "Ferris Bueller's Day Off" },
  { text: "Here's to the ones who dream, foolish as they may seem.", film: "La La Land" },
  { text: "All we have to decide is what to do with the time that is given to us.", film: "The Lord of the Rings: The Fellowship of the Ring" },
  { text: "Forget it, Jake. It's Chinatown.", film: "Chinatown" },
  { text: "I am serious. And don't call me Shirley.", film: "Airplane!" },
  { text: "If you build it, he will come.", film: "Field of Dreams" },
  { text: "Louis, I think this is the beginning of a beautiful friendship.", film: "Casablanca" },
  { text: "I ate his liver with some fava beans and a nice Chianti.", film: "The Silence of the Lambs" },
  { text: "Bond. James Bond.", film: "Dr. No" },
  { text: "You're only supposed to blow the bloody doors off!", film: "The Italian Job" },
  { text: "Run, Forrest, run!", film: "Forrest Gump" },
  { text: "Yippee-ki-yay.", film: "Die Hard" },
  { text: "I want to play a game.", film: "Saw" },
  { text: "Witness me!", film: "Mad Max: Fury Road" },
  { text: "It's not possible. No, it's necessary.", film: "Interstellar" },
  { text: "We are Groot.", film: "Guardians of the Galaxy" },
  { text: "Avengers, assemble.", film: "Avengers: Endgame" },
  { text: "I love you 3000.", film: "Avengers: Endgame" },
  { text: "I'm Mary Poppins, y'all!", film: "Guardians of the Galaxy Vol. 2" },
  { text: "Perfectly balanced, as all things should be.", film: "Avengers: Infinity War" },
  { text: "Everything is awesome!", film: "The Lego Movie" },
  { text: "I am speed.", film: "Cars" },
  { text: "Fish are friends, not food.", film: "Finding Nemo" },
  { text: "Adventure is out there!", film: "Up" },
  { text: "I never look back, darling. It distracts from the now.", film: "The Incredibles" },
  { text: "The cold never bothered me anyway.", film: "Frozen" },
  { text: "Oh, what a day! What a lovely day!", film: "Mad Max: Fury Road" },
  { text: "I can do this all day.", film: "Captain America: The First Avenger" },
  { text: "Part of the journey is the end.", film: "Avengers: Endgame" },
  { text: "Reality is often disappointing.", film: "Avengers: Infinity War" },
  { text: "In a world full of locked rooms, the man with the key is king.", film: "Sherlock" },
  { text: "Some men just want to watch the world burn.", film: "The Dark Knight" },
  { text: "That's my secret, Captain. I'm always angry.", film: "The Avengers" },
  { text: "The flower that blooms in adversity is the most rare and beautiful of all.", film: "Mulan" },
  { text: "Ohana means family. Family means nobody gets left behind or forgotten.", film: "Lilo & Stitch" },
  { text: "To infinity... and beyond!", film: "Toy Story" },
  { text: "Don't let anyone ever make you feel like you don't deserve what you want.", film: "10 Things I Hate About You" },
  { text: "I am no man.", film: "The Lord of the Rings: The Return of the King" },
  { text: "Clever girl.", film: "Jurassic Park" },
  { text: "Welcome to Jurassic Park.", film: "Jurassic Park" },
  { text: "Inconceivable!", film: "The Princess Bride" },
  { text: "As you wish.", film: "The Princess Bride" },
  { text: "I'll get you, my pretty, and your little dog too!", film: "The Wizard of Oz" },
  { text: "Toto, I've a feeling we're not in Kansas anymore.", film: "The Wizard of Oz" },
  { text: "I see you.", film: "Avatar" },
  { text: "Remember who you are.", film: "The Lion King" },
  { text: "It does not do to dwell on dreams and forget to live.", film: "Harry Potter and the Sorcerer's Stone" },
  { text: "If you want to view paradise, simply look around and view it.", film: "Willy Wonka & the Chocolate Factory" },
  { text: "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.", film: "The Silence of the Lambs" },
  { text: "Every day above ground is a great day. Remember that.", film: "Scarface" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", film: "Invictus" },
  { text: "We buy things we don't need with money we don't have to impress people we don't like.", film: "Fight Club" },
  { text: "Strange, isn't it? Each man's life touches so many other lives.", film: "It's a Wonderful Life" },
  { text: "Every man dies. Not every man really lives.", film: "Braveheart" },
  { text: "Go ahead, make my day.", film: "Sudden Impact" },
  { text: "All right, Mr. DeMille, I'm ready for my close-up.", film: "Sunset Boulevard" },
  { text: "We'll always have Paris.", film: "Casablanca" },
  { text: "Of all the gin joints in all the towns in all the world, she walks into mine.", film: "Casablanca" },
  { text: "Round up the usual suspects.", film: "Casablanca" },
  { text: "Play it, Sam. Play 'As Time Goes By.'", film: "Casablanca" },
  { text: "As God is my witness, I'll never be hungry again.", film: "Gone with the Wind" },
  { text: "They call me Mister Tibbs!", film: "In the Heat of the Night" },
  { text: "There's no crying in baseball!", film: "A League of Their Own" },
  { text: "Open the pod bay doors, HAL.", film: "2001: A Space Odyssey" },
  { text: "Yo, Adrian!", film: "Rocky" },
  { text: "Hello, gorgeous.", film: "Funny Girl" },
  { text: "Mrs. Robinson, you're trying to seduce me. Aren't you?", film: "The Graduate" },
  { text: "Plastics.", film: "The Graduate" },
  { text: "Gentlemen, you can't fight in here! This is the War Room!", film: "Dr. Strangelove" },
  { text: "Snap out of it!", film: "Moonstruck" },
  { text: "I want to be alone.", film: "Grand Hotel" },
  { text: "Love means never having to say you're sorry.", film: "Love Story" },
  { text: "Stella! Hey, Stella!", film: "A Streetcar Named Desire" },
  { text: "Wait a minute. You ain't heard nothin' yet!", film: "The Jazz Singer" },
  { text: "I have always depended on the kindness of strangers.", film: "A Streetcar Named Desire" },
  { text: "Shane. Shane. Come back!", film: "Shane" },
  { text: "Oh, Jerry, don't let's ask for the moon. We have the stars.", film: "Now, Voyager" },
  { text: "You know how to whistle, don't you? You just put your lips together and blow.", film: "To Have and Have Not" },
  { text: "What we've got here is failure to communicate.", film: "Cool Hand Luke" },
  { text: "Greed, for lack of a better word, is good.", film: "Wall Street" },
  { text: "Today, I consider myself the luckiest man on the face of the Earth.", film: "The Pride of the Yankees" },
  { text: "A boy's best friend is his mother.", film: "Psycho" },
  { text: "They're here!", film: "Poltergeist" },
  { text: "Listen to them. Children of the night. What music they make.", film: "Dracula" },
  { text: "It was beauty killed the beast.", film: "King Kong" },
  { text: "La-dee-da, la-dee-da.", film: "Annie Hall" },
  { text: "Life is a banquet, and most poor suckers are starving to death!", film: "Auntie Mame" },
  { text: "My mother thanks you. My father thanks you. My sister thanks you. And I thank you.", film: "Yankee Doodle Dandy" },
  { text: "I'm as mad as hell, and I'm not going to take this anymore!", film: "Network" },
  { text: "Do I feel lucky? Well, do ya, punk?", film: "Dirty Harry" },
  { text: "Made it, Ma! Top of the world!", film: "White Heat" },
];

function getDailyIndex() {
  var now = new Date();
  var dayOfYear = Math.floor((now - new Date(now.getFullYear(), 0, 0)) / 86400000);
  // Pseudo-random scatter using prime multiplier to avoid clustering
  var seed = (dayOfYear + now.getFullYear()) * 2654435761;
  return Math.abs(seed) % QUOTES.length;
}

export default function DailyQuote() {
  var quote = QUOTES[getDailyIndex()];
  return (
    <div className="flex items-center gap-2 px-1 pb-1 min-w-0" data-testid="daily-quote">
      <Quote className="w-3.5 h-3.5 text-primary/60 shrink-0 rotate-180" />
      <p className="text-xs text-white/80 italic leading-relaxed truncate">
        {quote.text}
      </p>
      <Quote className="w-3 h-3 text-primary/60 shrink-0" />
      <span className="text-xs not-italic text-yellow-400/80 shrink-0 whitespace-nowrap">— {quote.film}</span>
    </div>
  );
}
